name: geohackweek2019
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - adal=1.2.2
  - affine=2.2.2
  - alembic=1.0.11
  - altair=3.1.0
  - appdirs=1.4.3
  - asciitree=0.3.3
  - asn1crypto=0.24.0
  - async_generator=1.10
  - attrs=19.1.0
  - awscli=1.16.209
  - backcall=0.1.0
  - bleach=3.1.0
  - blinker=1.4
  - bokeh=1.3.1
  - boost-cpp=1.70.0
  - boto3=1.9.199
  - botocore=1.12.199
  - branca=0.3.1
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - cachetools=2.1.0
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.6.16
  - certipy=0.1.3
  - cffi=1.12.3
  - cfitsio=3.470
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.1
  - colorama=0.3.9
  - colorcet=2.0.1
  - configurable-http-proxy=4.1.0
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask=2.2.0
  - dask-core=2.2.0
  - dask-kubernetes=0.9.1
  - datashader=0.7.0
  - datashape=0.5.4
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - descartes=1.1.0
  - distributed=2.2.0
  - docutils=0.14
  - entrypoints=0.3
  - expat=2.2.5
  - fasteners=0.14.1
  - fiona=1.8.6
  - folium=0.10.0
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - fribidi=1.0.5
  - fsspec=0.4.0
  - gcsfs=0.3.0
  - gdal=2.4.1
  - geographiclib=1.49
  - geojson=2.4.1
  - geopandas=0.5.1
  - geopy=1.20.0
  - geos=3.7.2
  - geotiff=1.4.3
  - geoviews-core=1.6.2
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - google-auth=1.6.3
  - google-auth-oauthlib=0.4.0
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.9.0
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - holoviews=1.12.3
  - hvplot=0.4.0
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - intake=0.5.2
  - intake-xarray=0.3.0
  - ipykernel=5.1.1
  - ipyleaflet=0.11.1
  - ipympl=0.3.3
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.14.1
  - jinja2=2.10.1
  - jmespath=0.9.4
  - joblib=0.13.2
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.8.5
  - jsonschema=3.0.1
  - jupyter_client=5.3.1
  - jupyter_core=4.4.0
  - jupyterhub=1.0.0
  - jupyterlab=1.0.4
  - jupyterlab_server=1.0.0
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdap4=3.20.2
  - libedit=3.1.20170329
  - libffi=3.2.1
#  - libgcc-ng=9.1.0
  - libgdal=2.4.1
#  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libpq=11.4
  - libsodium=1.0.17
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
#  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.29.0
  - locket=0.2.0
  - lz4-c=1.8.3
  - mako=1.0.10
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mercantile=1.1.1
  - mistune=0.8.4
  - monotonic=1.5
  - msgpack-numpy=0.4.4.3
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nb_conda_kernels=2.2.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - nbgitpuller=0.7.0
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - networkx=2.3
  - nodejs=11.14.0
  - notebook=6.0.0
  - nteract_on_jupyter=2.0.12
  - numba=0.45.1
  - numcodecs=0.6.3
  - numpy=1.16.4
  - oauthlib=3.0.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1c
  - osmnx=0.10
  - owslib=0.18.0
  - packaging=19.0
  - palettable=3.2.0
  - pamela=1.0.0
  - pandas=0.25.0
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - panel=0.6.0
  - pango=1.42.4
  - param=1.9.1
  - parso=0.5.1
  - partd=1.0.0
  - patsy=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.1
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.4
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - psycopg2=2.8.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pyasn1=0.4.5
  - pyasn1-modules=0.2.5
  - pycparser=2.19
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pycurl=7.43.0.2
  - pyepsg=0.4.0
  - pygments=2.4.2
  - pyjwt=1.7.1
  - pykdtree=1.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysal=2.0.0
  - pyshp=2.1.0
  - pysocks=1.7.0
  - python=3.7.3
  - python-dateutil=2.7.5
  - python-editor=1.0.4
  - python-kubernetes=10.0.0
  - python-snappy=0.5.4
  - pytz=2019.2
  - pyviz_comms=0.7.2
  - pywavelets=1.0.3
  - pyyaml=5.1
  - pyzmq=18.0.2
  - qt=5.9.7
  - rasterio=1.0.24
  - rasterstats=0.13.1
  - readline=8.0
  - requests=2.22.0
  - requests-oauthlib=1.2.0
  - rio-cogeo=1.1.0
  - rsa=3.4.2
  - rtree=0.8.3
  - ruamel=1.0
  - ruamel.yaml=0.16.0
  - s3fs=0.3.1
  - s3transfer=0.2.1
  - sat-search=0.2.1
  - sat-stac=0.1.3
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - simplejson=3.16.0
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snuggs=1.4.6
  - sortedcontainers=2.1.0
  - sqlalchemy=1.3.6
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - supermercado=0.0.5
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.3.1
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - traittypes=0.2.1
  - tzcode=2019a
  - urllib3=1.25.3
  - utm=0.5.0
  - vincent=0.4.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - websocket-client=0.56.0
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - xarray=0.12.3
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.8
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - zlib=1.2.11
  - zstd=1.4.0
  - dask-labextension=1.0.3
