name: geohackweek2019
channels:
  - conda-forge
dependencies:
  - awscli=1.16
  - bokeh=1.3
  - boto3=1.9
  - botocore=1.12
  - branca=0.3
  - cartopy=0.17
  - curl=7.65
  - dask=2.2
  - dask-kubernetes=0.9
  - datashader=0.7
  - distributed=2.2
  - fiona=1.8
  - folium=0.10
  - gdal=2.4
  - geojson=2.4
  - geopandas=0.5
  - geopy=1.20
  - geoviews-core=1.6
  - graphviz=2.40
  - hdf4=4.2
  - hdf5=1.10
  - h5py=2.9
  - holoviews=1.12
  - hvplot=0.4
  - intake=0.5
  - intake-xarray=0.3
  - ipykernel=5.1
  - ipyleaflet=0.11
  - ipympl=0.3
  - ipywidgets=7.5
  - jupyterlab=1.0
  - libgdal=2.4
  - matplotlib=3.1
  - nb_conda_kernels=2.2
  - nbgitpuller=0.7
  - netcdf4=1.5
  - networkx=2.3
  - notebook=6.0
  - numpy=1.16
  - osmnx=0.10
  - owslib=0.18
  - pandas=0.25
  - panel=0.6
  - pillow=6.1
  - pip=19.2
  - proj4=5.2
  - pyepsg=0.4
  - pyproj=1.9
  - pyshp=2.1
  - python=3.7
  - pysal=2.0
  - psycopg2=2.8
  - rasterio=1.0
  - rasterstats=0.13
  - rio-cogeo=1.1
  - requests=2.22
  - s3fs=0.3
  - seaborn=0.9
  - gcsfs=0.3
  - sat-search=0.2
  - sat-stac=0.1
  - scikit-learn=0.21
  - scikit-image=0.15
  - scipy=1.3
  - shapely=1.6
  - tornado=6.0
  - utm=0.5
  - widgetsnbextension=3.5
  - xarray=0.12
  - zarr=2.3
